### PR TITLE
Update Fedora-CentOS contributions

### PR DESCRIPTION
**Pull request by daftaupe**

### CODE REVIEW

**Comment by imsodin** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@imsodin: Noted! Need another LGTM or explicit merge command.

**Comment by AudriusButkevicius** [comment]
@st-review lgtm

**Comment by st-review** [comment]
:ok_hand: Merged as 7e4d2d9fe62596f9dcc29baa27960d5f2b4de158. Thanks, @daftaupe!

**Comment by AudriusButkevicius** [comment]
This should add a post upgrade hook to send a sighub.

**Pull request closed without merging**
