### PR TITLE
fixed user systemd path

### PR DESCRIPTION
**Pull request by typekpb**

### CODE REVIEW

**Comment by imsodin** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@imsodin: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
@st-review lgtm

users/autostart: User systemd path

**Comment by st-review** [comment]
:ok_hand: Merged as 40071d81e4285cf49bc1252d877c8d7d5cb8b764. Thanks, @typekpb!

**Pull request closed without merging**
