### PR TITLE
Umask set in syncthing@.service

### PR DESCRIPTION
**Pull request by theincogtion**
Umask set in syncthing@.service

### CODE REVIEW

**Comment by Zillode** [comment]
ping @rumpelsepp

**Comment by AudriusButkevicius** [comment]
This is only relevant when syncing from windows, and it's not about correctness but about what you expect when you get stuff from windows. Plus it needs a note about ignore permissions setting.

**Comment by theincogtion** [comment]
Can I change my pull request?

**Comment by AudriusButkevicius** [comment]
You can do your modifications in the same branch via command line UI.
```
git add -u - to add modified fields
git commit --amend - to modify the last commit
git push origin <branchname> -f  -- to overwrite what the branch looks like.
```

If you've done it through the web ui, then you can just close this one and open a new one.

**Pull request closed without merging**
