### PR TITLE
Added a worked out scenario

### PR DESCRIPTION
**Pull request by asdf8dfafjk**
Give a scenario of 3 devices with disjoint availibility.

### CODE REVIEW

**Comment by tomasz1986** [comment]
Thank you for your contribution!

The current note considers a 2-device setup only, so it would probably be useful to have a 3-or-more-device setup described too, but I must say this is way too complex.

Some personal suggestions on how to improve the text:

- Use human-friendly names instead of shorthands like D1, D2, F1, etc. There's a reason for having "Bob" and "Alice" there, which is to make the description easier to understand, e.g. for beginners and non-techy people.
- Avoid cryptic abbreviations like "F1-D1-2", "F1-D1-3". The main reason is same as above, and also they get super confusing very quickly to anyone but the author 😉.
- The note is meant to provide quick information on what versioning is and is not. Please try to shorten the whole explanation and try to put it in more layman's terms.

**Comment by asdf8dfafjk** [comment]
Thank you for taking the time to comment and thanks of course for working on this for free. I think your first two points are obviously coming from someone experieneced but sadly I don't think I can shorten 3 anymore since I don't see much repetition in there. I'll address first two and then let you suggest something about point 3. 

I do think that this change in its entirety clarifies any question anyone might have about current state of versioning so even if long, its kind of "definitive"

**Comment by asdf8dfafjk** [comment]
Hopefully the mental model would now be a bit easy to make.

**Comment by asdf8dfafjk** [comment]
PS: I am not a citizen of any of 3 countries so this is a joke :)

**Comment by acolomb** [comment]
I don't think such a joke is appropriate for our documentation. And it will be quickly outdated when different politicians are elected.

Pease make sure to use a consistent wrapping in your new content. A maximum of 80 columns seems common in the documentation right now.

**Comment by asdf8dfafjk** [comment]
Sorry I didn't realize you guys were opposed to any kind of political jokes since the ukraine thing is so prominently displayed on your website. Anyway, I cannot spend further time on this.

**Comment by asdf8dfafjk** [comment]
I reopened this without committed political references,, hopefully this can be added.

That said, Fuck NATO, fuck western one sided media, and fuck weapons smuggling cocaine addict zelensky

**Pull request closed without merging**
