### PR TITLE
Move windows-syncthing-installer out of `unmaintained`

### PR DESCRIPTION
**Pull request by sodacode**
The installer still works exactly as intended.
Will be updating the installer with some new requested features soon.
(install as service, optional link in start menu / desktop)

### CODE REVIEW

**Comment by imsodin** [comment]
Its not really a GUI wrapper, but creating another category just for one installer is more confusion I think, so lgtm from me - but in a separate post, dont want any trouble with our friendly bot :)

**Comment by imsodin** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@imsodin: Noted! Need another LGTM or explicit merge command.

**Comment by canton7** [comment]
Make sure it doesn't start synching as local admin, etc.

**Comment by sodacode** [comment]
Okay, I'll re-open when ready.

**Pull request closed without merging**
