### PR TITLE
Windows does not support escaping (ref #2822)

### PR DESCRIPTION
**Pull request by ProactiveServices**

### CODE REVIEW

**Comment by calmh** [comment]
Thanks. However, more importantly it needs to describe that brackets are actually interpreted as character ranges, as this is currently not mentioned anywhere :)

**Comment by ProactiveServices** [comment]
I hadn't even noticed that was missing...too much regex in my life.

**Comment by calmh** [comment]
@st-review merge this please

**Comment by st-review** [comment]
OK, merged as cb62b52a3023b9849f3406dd3ef880658311fb4d. Thanks, @ProactiveServices!

**Pull request closed without merging**
