### PR TITLE
Updated with field information for /rest/db/file

### PR DESCRIPTION
**Pull request by jorgen-k**
See forum: https://forum.syncthing.net/t/how-to-know-that-a-file-is-in-sync-using-rest-api/5313/2?u=jorgen_k

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
So the fallback is not hash of the file but the id of the device (so that everyone agress on the resolution order)

**Comment by AudriusButkevicius** [comment]
Also perhaps worth metioning delete vs non-delete conflict. 

Btw mtime is only a sensible comparison insystems that don't modify it and are synced up. Syncthing only uses mtime for detecting changes and deciding a conflict. Newer mtime does not mean that that file is newer.

**Comment by jorgen-k** [comment]
About the hash, I think I have written that in the pull request, but you porbably just pointed out that my first thought in the forum was incorrect, right?

Do I need to update anything in repsect to the delete vs non-delete conflict? If so, do you have a suggestion on how to phrase it?

I am releived about your comment about mtime :-)

**Comment by AudriusButkevicius** [comment]
Also, numBlocks is number of blocks the file contains, version vector contains a list of device ids and their localVersion of the file, not version of blocks. Blocks don't have versions. Regarding deletes you should just say that non-deletion wins against deletion in case of conflict.

**Pull request closed without merging**
