### PR TITLE
updated compiler version

### PR DESCRIPTION
**Pull request by lkwg82**
see compiler change to version 1.6 in https://github.com/syncthing/syncthing/releases/tag/v0.12.20

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Now that I am thinking about it, it would probably still work with 1.3 if you'd use our build scripts.

**Comment by lkwg82** [comment]
what about the go1.5 vendors directory is this backward compatible?

**Comment by AudriusButkevicius** [comment]
yeah 1.5 it works with a special variable set

**Comment by calmh** [comment]
I reverted it. We *should* update this section a little as our build process now becomes a little different in 1.3-1.4, 1.5 and 1.6. However we *do* still build correctly on 1.3 and 1.4, the dependencies just need different handling. I'll write something up, thanks for bringing this to our attention.

**Comment by calmh** [comment]
I pushed https://github.com/syncthing/docs/commit/7079b3f0c9257005722bd6eab929f42326de820c to clarify the situation.

**Pull request merged**
