### PR TITLE
add Webi to list of installers

### PR DESCRIPTION
**Pull request by coolaj86**
See https://webinstall.dev/syncthing

### CODE REVIEW

**Comment by calmh** [comment]
Thanks! This looks like it could go once into a new "Cross Platform" heading under packagers, yes?

**Comment by st-review** [comment]
:robot: *beep boop*

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Comment by coolaj86** [comment]
Sorry, @calmh I didn't notice your question earlier.

It's a tricky one because most people don't search for "cross platform" but rather they search for "Windows" or "Mac" or "Linux". That said, whatever you think is most useful or best I'm open to.

Would you like me to create a new PR with a new section? If so, where should the new section go?

**Comment by calmh** [comment]
"cross platform" is listed at the top for gui wrappers, it would seem to make sense to have a similar section for packagings. You can mention the supported platforms explicitly in the entry in question if you want to be sure to catch people ctrl-f:ing the page.

**Comment by coolaj86** [comment]
@calmh Updated. How's that?

**Comment by coolaj86** [comment]
Preview link: https://github.com/coolaj86/docs/blob/patch-1/users/contrib.rst#cross-platform-1

**Review by calmh — APPROVED** [review]

**Pull request merged**
