### PR TITLE
dev/mergebot: Warning about mixing st-review and conversation

### PR DESCRIPTION
**Pull request by imsodin**
https://forum.syncthing.net/t/st-review-behaviour/9298/3
syncthing/docs#298

### CODE REVIEW

**Comment by ProactiveServices** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@ProactiveServices: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as 19f887669589fa5e5cecb852d5639212360191a8. Thanks, @imsodin!

**Pull request closed without merging**
