### PR TITLE
Updated SSH tunneling command

### PR DESCRIPTION
**Pull request by mclang**
Added parameters -f and -N so that SSH tunnel is created in the background without opening shell.

### CODE REVIEW

**Comment by calmh** [comment]
I suspect this will just cause more confusion about what happened, for the people unfamiliar with these options. Those familiar with them will already know what to do.

**Comment by mclang** [comment]
Well I didn't remember, I had to look for the right parameters.
Maybe this possibility should be added as another command, or explained better to prevent confusion?

**Comment by calmh** [comment]
Oh, I don't know those by heart either. I just think that since this document is explaining ssh forwarding to someone who may never have used it at all, ever, keeping it as simple as possible is a win.

**Comment by mclang** [comment]
So you think that leaving current command as it is and adding another example like what I am proposing as alternative is also too confusing for new users?

**Comment by ProactiveServices** [comment]
If by default, or in most cases, the example command doesn't work, I'd suggest that the example should be "fixed" to include the extra parameters. Otherwise it should be left as it is, since it's not our place to document `ssh`.

**Comment by JohnVeness** [comment]
I agree it isn't the place of Syncthing to document ssh. If you went down that route, all you've documented so far is a command-line method, whereas it is also possible to do ssh tennelling using, for example, ConnectBot in Android, or PuTTY in Windows, and you don't really want to start documenting all those other ways of doing things.

I wonder, is there a generic "ssh tunnelling" instructions on a well-maintained website (a bit like https://portforward.com/) that can be pointed to? Then you could just say something like "You can use SSH tunnelling to access the web interface from another computer, see XXXXX.com".

**Comment by ProactiveServices** [comment]
@mclang care to take another look at your proposal and the comments since?

**Comment by mclang** [comment]
Sorry, I somehow missed notifications about this

Link to compiled docs gives 404, so I can't check them.

You are right, it is no place for Syncthing to start documenting all things SSH can do, so I back away and close this pull request.

Cheers!

**Pull request closed without merging**
