### PR TITLE
users/autostart: Also refer to the repo for .desktop files

### PR DESCRIPTION
**Pull request by imsodin**

### CODE REVIEW

**Comment by acolomb** [comment]
Isn't this already included in the paragraph below?

**Comment by imsodin** [comment]
Sorry about this, rebased.

**Comment by tomasz1986** [comment]
The link formatting seems broken (see the deploy preview), but as @acolomb mentioned above, the exact same link is already listed right below this paragraph. Is it necessary to list it twice like that?

**Comment by imsodin** [comment]
Fixed the link.

And yes, some hint is necessary, see https://forum.syncthing.net/t/autostart-on-manjaro/17963

**Review by acolomb — APPROVED** [review]

**Pull request merged**
