### PR TITLE
dev/mergebot: Describe LGTM flow

### PR DESCRIPTION
**Pull request by calmh**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@AudriusButkevicius: Noted! Need another LGTM or explicit merge command.

**Comment by rumpelsepp** [comment]
@st-review lgtm

**Comment by st-review** [comment]
:ok_hand: Merged as 936cef6ddd6bd6ce1d7dfd8961785452d89b195b. Thanks, @calmh!

**Pull request closed without merging**
