### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by HairyFotr**

### CODE REVIEW

**Comment by imsodin** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@imsodin: Noted! Need another LGTM or explicit merge command.

**Comment by canton7** [comment]
@st-review lgtm

**Comment by st-review** [comment]
:ok_hand: Merged as afe4398d78e54019a8e663581aadcf4cdfb3b386. Thanks, @HairyFotr!

**Comment by canton7** [comment]
Will you look at that! Me and st-review managed to work together for once...

**Pull request closed without merging**
