### PR TITLE
Reduced Ambiguity in "Why does it use…"

### PR DESCRIPTION
**Pull request by Thovthe**
If this is accurate, I think it's valuable to spell it out clearly for anyone who may be concerned about security but also too (insert reason here) to confirm.

### CODE REVIEW

**Comment by Thovthe** [comment]
Not sure why anything is breaking, simply a markdown document change.

**Comment by canton7** [comment]
Don't think it's you.

```
10:53:22 PM: /usr/local/bin/build: line 32: sphinx-build: command not found
```

@calmh?

**Comment by AudriusButkevicius** [comment]
Yet the change has typos in the word always and I think it makes the sentence harder to process

**Comment by calmh** [comment]
Merged with tweaks, thanks.

**Pull request closed without merging**
