### PR TITLE
Document -umask option.

### PR DESCRIPTION
**Pull request by DanielO**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Is there a thing like that? Why can't you set the umask in the shell before starting?

**Comment by DanielO** [comment]
I did try that but the FreeBSD rc.d script already has 2 lots of escaping to change UID then wrap syncthing with daemon (to write a PID file and redirect logging) that it was simpler to modify the syncthing code..

Arguably daemon could grow a umask option but that's a lot slower to change :)

**Comment by AudriusButkevicius** [comment]
I think we should discuss it on the actual or. My bad on discovering this first.

**Comment by DanielO** [comment]
OK, sure.

**Pull request closed without merging**
