### PR TITLE
Update getting-started.rst

### PR DESCRIPTION
**Pull request by tommodore**
add whitespaces due to copy-paste issues.

### CODE REVIEW

**Comment by rumpelsepp** [comment]
?

**Comment by tommodore** [comment]
For our internal documentation i copy paste a few parts of the documentation. These whitespaces are missing due to line breaks. It's a stupid thing, but maybe helpful for others.

**Comment by rumpelsepp** [comment]
What's the actual benefit of adding a trailing and an intermediate whitespace?

**Comment by AudriusButkevicius** [comment]
Sorry, but I think the current version is better :dancers:

**Pull request closed without merging**
