### PR TITLE
Resolve sync conflicts bash script.

### PR DESCRIPTION
**Pull request by dschrempf**
See also

https://forum.syncthing.net/t/small-bash-script-to-resolve-conflicts/9269

### CODE REVIEW

**Comment by imsodin** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@imsodin: Noted! Need another LGTM or explicit merge command.

**Comment by ProactiveServices** [comment]
@st-review lgtm

**Comment by st-review** [comment]
:ok_hand: Merged as 56720376ba03897be6204440be6be55b5e060f9c. Thanks, @dschrempf!

**Pull request closed without merging**
