### PR TITLE
users/syncthing: Update current CLI args, envvars and debug levels

### PR DESCRIPTION
**Pull request by ProactiveServices**
WIP - need input for the deadlock-related envvars, please.

Minor grammar changes, removed unused debug levels.
Re-worded the debug explaination to be consistent with description in the code.
Ordered debug facilities into rough groups to aid the reader.

### CODE REVIEW

**Comment by ProactiveServices** [comment]
Note: Wait for `-reset-delta` and `-reset-database` release before slapping this online

**Comment by ProactiveServices** [comment]
I'm fairly sure this now makes dev/debugging redundant. I took a look through the docs to see how best to replace references to debugging.rst but I'm a but unsure how to do this properly.

**Comment by calmh** [comment]
❤️

There are things I want in dev/debugging that is not what is there now, actual info on things to do, so hopefully I'll get around to fixing that at some point.

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as ab141a17aef26f2ebbd1608b7a35eefcd28688b3. Thanks, @ProactiveServices!

**Pull request closed without merging**
