### PR TITLE
dev/rest: Introducing missing event types (fixes #80)

### LINKED ISSUE #80: Document missing events
Looks like these events are new to v0.12?

### PR DESCRIPTION
**Pull request by imsodin**
Update event documentation: Specify since as optional, as it actually is in the code and is also used thus for the web GUI and add missing events.

### CODE REVIEW

**Comment by imsodin** [comment]
Not lgtm, found another stupidity of mine. I should always delete _build to catch all warnings...
Give me a moment

**Comment by imsodin** [comment]
So, now there is no more new sphinx warnings introduces by this and is IMO fine.

**Comment by ProactiveServices** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@ProactiveServices: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
@st-review merge (don't think persistent lgmts where implemented when they were given above, sorry)

**Comment by st-review** [comment]
:ok_hand: Merged as a44642fdb12baba9ffbb87d6bd09329f5f3a687b. Thanks, @imsodin!

**Pull request closed without merging**
