### PR TITLE
Update config.rst

### PR DESCRIPTION
**Pull request by bugith**
document defaultFolderPath

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
"and this can" should just be a new sentence.

**Comment by imsodin** [comment]
@st-review merge

users/config: Document defaultFolderPath

**Comment by st-review** [comment]
@imsodin: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as ed56725708619162783a5547cb02903a5f06642a. Thanks, @bugith!

**Pull request closed without merging**
