### PR TITLE
fix: new /rest/config/insync api path

### PR DESCRIPTION
**Pull request by evrins**
fix new /rest/config/insync api path

https://docs.syncthing.net/rest/system-config-insync-get.html 

should use /rest/config/insync instead

### CODE REVIEW

**Comment by calmh** [comment]
The new path exists, but the old path is still used and mentioned in a lot of other places. I'm not sure we should just switch to the new one here. (Or even if the new one should exist under this name at all...  Since it's new, it might have been something more descriptive like `/rest/config/restart-required` or something.)

**Comment by imsodin** [comment]
This PR just changes a typo of mine when introducing the new `/rest/config/...` endpoints - the `/rest/config/insync` endpoint already exists unfortunately. If we want to switch to something more descriptive like the proposed `/rest/config/restart-required` that needs to happen on the go side of things too. Given how new `/rest/config/insync` is I'd just not mention it in the docs at all then.

**Comment by imsodin** [comment]
@evrins I added a `/rest/config/restart-required` endpoint. Could you please change this PR to use that one instead.

**Comment by st-review** [comment]
:robot: *beep boop*

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Pull request closed without merging**
