### PR TITLE
user/config: Update configuration elements

### PR DESCRIPTION
**Pull request by imsodin**
<strike>Do *not review or merge*, I just want this to be out there so that everyone else can use it.

I started updating the config elements but it isn't finished and I don't know when/if I'll finish, so if anyone intends to do the same, feel free to use this as a starting point.</strike>

### CODE REVIEW

**Comment by imsodin** [comment]
Now I am finished with this, please have a look at it.

In the end I didn't have the patience to look up what all the KCP params do, but I guess "various tweaking parameters" is good enough for anyone not diving into the code - otherwise @AudriusButkevicius is welcome to elaborate ;)

**Comment by imsodin** [comment]
Now I am finished with this, please have a look at it.

In the end I didn't have the patience to look up what all the KCP params do, but I guess "various tweaking parameters" is good enough for anyone not diving into the code - otherwise @AudriusButkevicius is welcome to elaborate ;)

And here is the rendered version: https://build.syncthing.net/repository/download/Documentation_Build/13259:id/html.tar.gz%21/users/config.html

**Comment by calmh** [comment]
Awesome. Thanks for going through this!

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as f0d0a05fa550d06063631cb9f210ee762352279b. Thanks, @imsodin!

**Pull request closed without merging**
