### PR TITLE
dev/mergebot: Emphasize the importance of getting the "Skip-check: authors" part right

### PR DESCRIPTION
**Pull request by calmh**

### CODE REVIEW

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
Hmm...

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
\o/

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as 899b9fc6c718f0c6a24c2c1dd74a25f972158941. Thanks, @calmh!

**Pull request closed without merging**
