### PR TITLE
users/syncthing:  Add -auditfile

### PR DESCRIPTION
**Pull request by ProactiveServices**
Few other minor improvements

### CODE REVIEW

**Comment by ProactiveServices** [comment]
Ref https://github.com/syncthing/syncthing/pull/3860

**Comment by ProactiveServices** [comment]
Not sure about `[-auditfile=<file|-|-->]` as it looks clumsy.

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as d8cd8bb7c600af1634cff2bd4dcb1552a0d2732d. Thanks, @ProactiveServices!

**Pull request closed without merging**
