### PR TITLE
users/config: Add ID to each config option for easy referencing

### PR DESCRIPTION
**Pull request by tomasz1986**
Assign an ID to each config option, so that we can easily refer with an
URL to a specific one when needed. Use more specific IDs than before in
order to prevent conflicts between same options under different elements,
e.g. folder-id and device-id should be separate.

Signed-off-by: Tomasz Wilczyński <twilczynski@naver.com>

### CODE REVIEW

**Comment by tomasz1986** [comment]
The CSS change is required to make everything look the same as before, because Sphinx formats each element as a separate `dl`. I have tried hard to make it add IDs to the existing `dt`s instead, but it just does not seem possible with RST, i.e. it is impossible to add an ID to a specific element and also give the ID a different value than the element's text.

**Comment by st-review** [comment]
:robot: *beep boop*

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Comment by AudriusButkevicius** [comment]
Perhaps I should have left it closed, or do you plan on finishing this?

**Comment by tomasz1986** [comment]
> Perhaps I should have left it closed, or do you plan on finishing this?

I do, but probably only in late June/July, when I have more free time to spend. Shouldn't the stalled pull requests re-open themselves if there are new commits anyway?

**Comment by AudriusButkevicius** [comment]
Idk, but I guess I'll close it and we will see.

**Comment by acolomb** [comment]
Superseded by #710.

**Pull request closed without merging**
