### PR TITLE
users/syncthing: Polish envvar / parameter docs

### PR DESCRIPTION
**Pull request by ProactiveServices**
Replace STDEADLOCK-related envvars with dragons
Improve --norestart to briefly describe changes to monitor behaviour
Add STNORESTART envvar docs

### CODE REVIEW

**Comment by imsodin** [comment]
@st-review lgtm

**Comment by st-review** [comment]
:hand: I'm sorry, @imsodin. I'm afraid I can't do that.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as ec927c07a39e555b8e677254ce09578bd06ba863. Thanks, @ProactiveServices!

**Pull request closed without merging**
