### PR TITLE
Add a link to the official Gentoo package

### PR DESCRIPTION
**Pull request by sbraz**
It's been officially part of the Gentoo tree for a while now :)

### CODE REVIEW

**Comment by calmh** [comment]
Should this then just say something like "use your regular package manager"? :)

**Comment by sbraz** [comment]
Well, other distros use links as well, so I thought I'd try to stay consistent. But I can change it if you want me to.

**Comment by calmh** [comment]
No, you're right

**Comment by calmh** [comment]
@st-review merge it, it's good

**Comment by st-review** [comment]
:ok_hand: Merged as f6b4c34187ee2c54b21ce9024ad5fd6c7776aa0e. Thanks, @sbraz!

**Pull request closed without merging**
