### PR TITLE
Fix sphinx warning

### PR DESCRIPTION
**Pull request by letiemble**
Remove the warning due to a bad identation.

### CODE REVIEW

**Comment by calmh** [comment]
Should this be indented at all, to begin with?

**Comment by calmh** [comment]
Looks like it probably should

**Comment by calmh** [comment]
@st-review merge this please

Indent URL under unofficial CentOS packages

**Comment by st-review** [comment]
OK, merged as f27f6dff3c79f69c4f4109bfde250b75638be7be. Thanks, @letiemble!

**Pull request closed without merging**
