### PR TITLE
dev/device-ids.rst, users/contrib.rst: Update supported links to use https

### PR DESCRIPTION
**Pull request by scienmind**
As the title goes

(Edit: Disregard the abundance of commits, it's due to the mishandled rebasing earlier.
As seen in the diff only 2 files are actually altered in comparison to current master)

### CODE REVIEW

**Comment by imsodin** [comment]
@st-review lgtm

st-review will squash this when committing, right?

**Comment by st-review** [comment]
:hand: I'm sorry, @imsodin. I'm afraid I can't do that.

**Comment by st-review** [comment]
:hand: I'm sorry, @imsodin. I'm afraid I can't do that.

**Comment by calmh** [comment]
@st-review merge it

dev/device-ids, users/contrib: Update supported links to use https

**Comment by st-review** [comment]
:ok_hand: Merged as 64c82177cd381007a3331e65f89a21221303668a. Thanks, @scienmind!

**Comment by calmh** [comment]
@imsodin that seems like a bug, I'll check it out

**Comment by st-review** [comment]
@calmh: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
@imsodin it was a bug in loading collaborators per repo; this one has a lot of them. Fixed now!

**Pull request closed without merging**
