### PR TITLE
Add Asustor NAS and Rockstor as platforms and OS names for NAS platforms

### PR DESCRIPTION
**Pull request by alexvoda**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
you need to align the underline with the text

**Comment by AudriusButkevicius** [comment]
Also no idea what these things are

**Comment by rumpelsepp** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as d3a941dc634950cf174baf9025d4df7068e3e369. Thanks, @alexvoda!

**Comment by alexvoda** [comment]
Corrected the underlining.
Asustor is a network appliance manufacturer (like Synology or QNAP) and a subsidiary of ASUS.
Rockstor is a free, open source OS for NAS appliances based on Linux, BTRFS and Docker.
DSM (DiskStation Manager) is the name of the (Linux based) OS on Synology NAS boxes.
QTS is the name of the OS on QNAP NAS boxes.

**Comment by rumpelsepp** [comment]
> Also no idea what these things are

NAS distros.

**Pull request closed without merging**
