### PR TITLE
Create and enable manpages

### PR DESCRIPTION
**Pull request by rumpelsepp**
So here you go. This pr enables and creates the manpages which I mentioned in this forum post: https://forum.syncthing.net/t/documentation-move-again/2861/4?u=rumpelsepp

### CODE REVIEW

**Comment by calmh** [comment]
Nice! Needs rebase.

**Comment by rumpelsepp** [comment]
I am afraid that I have messed up my repo, since I submited #3 from my master branch... Rebasing against the upstream branch is quite a bit… annoying now. :D

**Comment by rumpelsepp** [comment]
rebased.

**Comment by calmh** [comment]
:+1::exclamation:

**Comment by calmh** [comment]
We'll sort something to get them built and included in packages etc...

**Comment by rumpelsepp** [comment]
I have emailed with the arch maintainer today. They most likely will pull them from github and adjust their buildscripts. The only problem I see is "how do we map a particular syncthing release to a particular revision of the docs?"

**Pull request merged**
