### PR TITLE
Update contrib.rst

### PR DESCRIPTION
**Pull request by ili-codes**
Added my "SyncthingLauncher" app

### CODE REVIEW

**Comment by calmh** [comment]
What is it? The git repo seems to contain compiled binaries only.

**Comment by ili-codes** [comment]
@calmh The git repo has the .scpt file.
https://github.com/ili-codes/SyncthingLauncher/blob/master/SyncthingLauncher.scpt

Open with Script Editor (Applications > Utilities).

**Comment by calmh** [comment]
@st-review merge it, good to go

**Comment by st-review** [comment]
:ok_hand: Merged as 1a8dbc105849e20a3db50676b57887fca13470c9. Thanks, @ili-codes!

**Pull request closed without merging**
