### PR TITLE
adds hint on debugging with delve

### PR DESCRIPTION
**Pull request by lkwg82**
depends on syncthing/syncthing/pull/4633

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Does that work, I use LiteIDE which has GDB support.

**Comment by lkwg82** [comment]
yes, I just use it to learn the code.

**Comment by imsodin** [comment]
Any reason not to use the usual commit format and the review bot to squash commits?

**Comment by lkwg82** [comment]
@imsodin I think the review bot is not active on docs? This project is configured differently.

**Comment by imsodin** [comment]
@lkwg82 It is active here, see e.g. https://github.com/syncthing/docs/pull/358

**Comment by lkwg82** [comment]
ah ok, my fault.

**Pull request merged**
