### PR TITLE
dev/event: Update event API (fixes #290)

### LINKED ISSUE #290: Document Event API changes
syncthing/syncthing#3941

### PR DESCRIPTION
**Pull request by imsodin**
See syncthing/syncthing#3941

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@AudriusButkevicius: Noted! Need another LGTM or explicit merge command.

**Comment by canton7** [comment]
@st-review LGTM too

**Comment by st-review** [comment]
@canton7: Noted! Need another LGTM or explicit merge command.

**Comment by canton7** [comment]
Ah, I think it interpreted that as a new commit message...?

**Comment by imsodin** [comment]
Let's see if we can trick st-review into accepting the authors lgtm instead of canton7's xD

@st-review lgtm

**Comment by st-review** [comment]
:ok_hand: Merged as 5f3de514bf13a71b15e22cf028979d01d93a6206. Thanks, @imsodin!

**Comment by st-review** [comment]
@imsodin: Noted! Need another LGTM or explicit merge command.

**Comment by canton7** [comment]
Don't think that quite had the desired effect >< https://github.com/syncthing/docs/commit/5f3de514bf13a71b15e22cf028979d01d93a6206

**Comment by imsodin** [comment]
I know, "too" would have been a much better commit message than this...
https://forum.syncthing.net/t/st-review-behaviour/9298

**Pull request closed without merging**
