### PR TITLE
rest/system-config-get: Added exemplary data

### PR DESCRIPTION
**Pull request by Zillode**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
The overhead of maintaining this is fenomenal though :/

**Comment by Zillode** [comment]
Agreed, but now I have to check at every new (major) release what fields were added, removed or updated. If we track it here it becomes more obvious what has changed.

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as 34b34c7b77466395ba560ed8ed9f87e7ffd8b342. Thanks, @Zillode!

**Comment by calmh** [comment]
Bonus points for someone to auto generate all this :)

**Pull request closed without merging**
