### PR TITLE
Update contrib.rst with munin-syncthing new URL

### PR DESCRIPTION
**Pull request by daftaupe**

### CODE REVIEW

**Comment by imsodin** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@imsodin: Noted! Need another LGTM or explicit merge command.

**Comment by AudriusButkevicius** [comment]
@st-review lgtm

**Comment by st-review** [comment]
:ok_hand: Merged as 51a2a95630d3da2d474012a3b3730615e7c70e65. Thanks, @daftaupe!

**Pull request closed without merging**
