### PR TITLE
Add additional information on transfer rates UI

### PR DESCRIPTION
**Pull request by StefanKopieczek**
Explain the number in parenthesis to the right of the current transfer speed, and also mention that the unit of the current speed can be toggled by clicking.

### CODE REVIEW

**Comment by imsodin** [comment]
I think it is the total amount of data already transferred, not the data to be transferred.

**Comment by StefanKopieczek** [comment]
It wasn't totally clear to me what the right-hand number in "Download Rate" or "Upload Rate" signified, especially because I noticed it seemed to fluctuate up and down without me touching the files in the underlying folder.
Had a quick peek at the code and I think I'm correct that it's the total data to be synced – so figured I'd update the docs to help others. Let me know if not, or if you'd like the wording altered at all.

Cheers!

**Comment by StefanKopieczek** [comment]
Amended. Thanks @imsodin !

**Comment by calmh** [comment]
@st-review merge

intro/gui: Add additional information on transfer rates

**Comment by st-review** [comment]
:ok_hand: Merged as 5caf3bcadc371ebccdb85747e52af15396ce8dc8. Thanks, @StefanKopieczek!

**Pull request closed without merging**
