### PR TITLE
faq.rst: Nested Syncthing folders

### PR DESCRIPTION
**Pull request by novoid**
for details see https://github.com/syncthing/docs/issues/269

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
They are not handled in any way, tested or recommended, yet people use them anyway. Potential side-effects might be extra network bandwidth and extra cpu usage for no good reason, potentially conflicts and potentially failure to sync (as both folders try to download the same file stepping on each others toes).

Ignores are not handled in any special way as .stignore is only meaningful at the root of the folder.

**Comment by ProactiveServices** [comment]
I'd avoid listing what pitfalls there are, in case people (smart enough to try it) assume it's an exhaustive list. "Do not nest shared folders. This behaviour is in no way supported, recommended or coded for in any way, and comes with many pitfalls."

**Comment by ProactiveServices** [comment]
@novoid Any updates on this?

**Comment by novoid** [comment]
@ProactiveServices I am not sure how this process should be done.

I thought I submit the question for the faq.rst via pull request and someone from SyncThing is going to apply the pull request and adding the official answer with it.

**Comment by ProactiveServices** [comment]
Pull requests are for contributing directly to a project - so commit some changes with the wording that you think is correct and we can discuss it here. Don't be shy :-)
If you'd just like to discuss something, rather than directly contribute, the forum is a more suitable place.  Any sort of help is welcome, even if it's just to start a conversation.

**Comment by AudriusButkevicius** [comment]
Perhaps I would not be so strict. I'd say that it's not officially supported, yet there are reported of people using them anyway.

**Comment by novoid** [comment]
I updated my pull request with an answer.

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as a53edbbab3bcdd5b3343bf3f3971a2d4c66bfcaa. Thanks, @novoid!

**Pull request closed without merging**
