### PR TITLE
users/config: Describe default-ignore approach

### PR DESCRIPTION
**Pull request by salim-b**
I've only now realized how easy it is to sync (potentially) device-independent dot files (and other config files) between computers and would have loved to learn that the first time I read this documentation section. So I added a paragraph describing it.

### CODE REVIEW

**Review by acolomb — CHANGES_REQUESTED** [review]
I think this should be moved to the `users/ignoring` section, although there is already an example there.  The paragraph above here is talking explicitly about syncing Syncthing's *own* configuration, which could potentially have bad effects.  A link to the other section could still be added.

Note that this should not be confused with the "default ignores" feature introduced some months ago.   There's #712 still in need of attention for that part of the configuration.  What you mean is more of an "ignore all, except some" approach, for which the term "default" ignores should not be used.

**Comment by salim-b** [comment]
> I think this should be moved to the `users/ignoring` section, although there is already an example there. The paragraph above here is talking explicitly about syncing Syncthing's *own* configuration, which could potentially have bad effects. A link to the other section could still be added.

Funny, I didn't read the **Syncing Configuration Files** section that way because it essentially applies to user configuration files of almost any software, not only syncthing's own. I'm not sure whether `users/ignoring` is the ideal place to put my addition then. Would a dedicated FAQ entry be more appropriate @acolomb ?

> Note that this should not be confused with the "default ignores" feature introduced some months ago. (...)

Ok, thanks for the hint. I agree that I need to change my terminology.

**Comment by acolomb** [comment]
I'm curious, how did you get to the configuration format page then?  What were you searching for?

I agree there is no proper "best practices" section in here, where stuff like this would belong.  There was some effort toward that in the past, but unfortunately stalled at some point.

Finding the info in the "Ignoring" section is not easy, I agree.  But it's the most on-topic we have right now, and the config file format page is definitely not the right place for such recommendations.

**Comment by st-review** [comment]
:robot: *beep boop*

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Pull request closed without merging**
