### PR TITLE
lib/config: Fix unfinished config elements from #355 (fixes #357)

### LINKED ISSUE #357: Wrong description for STUN options
I was looking for an explanation what the `<stunServer>` option should be set to when I don't want to use any (only IPv6 external connectivity). The documentation on the corresponding options (`<stunKeepaliveSeconds>` as well) just contains some unrelated copy-and-paste residue:

[blob/master/users/config.rst](https://github.com/syncthing/docs/blob/master/users/config.rst#options-element)

### PR DESCRIPTION
**Pull request by imsodin**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
We should mention that default value gets expanded to those, and that stun keepalive is how frequently we contact the stun server to maintain NAT mapping. Setting it to 0 disables contacting stun servers.

**Comment by imsodin** [comment]
@AudriusButkevicius done. Please edit if the STUN/KCP wording doesn't really fit, I don't know that lingo.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as 6b8e8349d223ef8b503e4d29386096b284fbe4b4. Thanks, @imsodin!

**Pull request closed without merging**
