### PR TITLE
Add gnome extension to user contribs

### PR DESCRIPTION
**Pull request by njam**
I was looking for something like this and was wondering why it's not mentioned in the contributions list.
I'm not the author, @jaystrictor is it ok to add it here?

### CODE REVIEW

**Comment by imsodin** [comment]
Thanks for the contribution, looks like a neatly done integration. To keep in line with existing headers, I would use "Linux" instead of "Gnome" and then explain shortly what it is (gnome tray integration).

**Comment by jaystrictor** [comment]
@njam Sure, with pleasure.

**Comment by njam** [comment]
@imsodin I force pushed a new version, wdyt?
I'm avoiding the term "tray" because there *was* a concept called "tray" in GNOME Shell, but it was removed in 3.26.

**Comment by imsodin** [comment]
@st-review merge

users/contrib: Add gnome shell extension

**Comment by st-review** [comment]
:ok_hand: Merged as c00776f5e0efbbc4eaa85672747c79d3f41e80bb. Thanks, @njam!

**Pull request closed without merging**
