### PR TITLE
users/contrib: Add classicsc/syncthingmanager

### PR DESCRIPTION
**Pull request by classicsc**

### CODE REVIEW

**Comment by imsodin** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@imsodin: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
@lgtm

**Comment by calmh** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@calmh: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
@st-review merge it then

**Comment by st-review** [comment]
:ok_hand: Merged as 50c41a1485b33b8525a7a0c99a59d35ecf269299. Thanks, @classicsc!

**Pull request closed without merging**
